# Generated by Django 4.1.2 on 2022-10-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_poster", models.CharField(max_length=100)),
                ("song_name", models.CharField(max_length=100)),
                ("artist_name", models.CharField(max_length=100)),
                ("album_name", models.CharField(max_length=100)),
                ("song_link", models.CharField(max_length=100)),
                ("attempted_lyrics", models.TextField(max_length=250)),
            ],
        ),
    ]
