# Generated by Django 4.1.2 on 2022-10-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song", name="upvotes", field=models.IntegerField(null=True),
        ),
    ]
