# Generated by Django 4.1.2 on 2022-10-30 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_song_upvotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="attempted_lyrics",
            field=models.TextField(max_length=255),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main_app.song"
                    ),
                ),
            ],
        ),
    ]
