# Generated by Django 4.1.2 on 2022-10-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_alter_song_attempted_lyrics_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_upvotes",
            field=models.IntegerField(null=True),
        ),
    ]
