# Generated by Django 4.1.2 on 2022-10-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_comment_comment_upvotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="song_comment",
            field=models.TextField(max_length=255, null=True),
        ),
    ]
