# Generated by Django 4.1.2 on 2022-11-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_comment_song_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre_name",
                    models.CharField(
                        choices=[
                            ("P", "Pop"),
                            ("R", "Rock"),
                            ("RB", "R&B"),
                            ("H", "Hip Hop"),
                            ("J", "Jazz"),
                            ("C", "Country"),
                            ("T", "Techno"),
                            ("D", "Dubstep"),
                            ("E", "EDM"),
                        ],
                        default="P",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="song",
            name="genre",
            field=models.ManyToManyField(to="main_app.genre"),
        ),
    ]
