# Generated by Django 4.1.2 on 2022-11-04 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_genre_song_genre"),
    ]

    operations = [
        migrations.RemoveField(model_name="song", name="genre",),
        migrations.AddField(
            model_name="genre",
            name="song",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.song",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="genre_name",
            field=models.CharField(
                choices=[
                    ("P", "Pop"),
                    ("R", "Rock"),
                    ("RB", "R&B"),
                    ("H", "Hip Hop"),
                    ("J", "Jazz"),
                    ("C", "Country"),
                    ("T", "Techno"),
                    ("D", "Dubstep"),
                    ("E", "EDM"),
                ],
                default="P",
                max_length=2,
                null=True,
            ),
        ),
    ]
