# Generated by Django 4.1.2 on 2022-11-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_remove_song_genre_genre_song_alter_genre_genre_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="genre_name",
            field=models.CharField(
                choices=[
                    ("P", "Pop"),
                    ("R", "Rock"),
                    ("RB", "R&B"),
                    ("H", "Hip Hop"),
                    ("J", "Jazz"),
                    ("C", "Country"),
                    ("T", "Techno"),
                    ("D", "Dubstep"),
                    ("E", "EDM"),
                ],
                default="---",
                max_length=2,
                null=True,
            ),
        ),
    ]
