# Generated by Django 3.2.6 on 2022-11-08 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_alter_genre_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(choices=[('P', 'Pop'), ('R', 'Rock'), ('RB', 'R&B'), ('H', 'Hip Hop'), ('J', 'Jazz'), ('C', 'Country'), ('T', 'Techno'), ('D', 'Dubstep'), ('E', 'EDM')], default='P', max_length=2),
        ),
    ]
